##install and import

In [1]:
pip install dgl

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.9/5.9 MB 45.8 MB/s eta 0:00:00


In [2]:
!pip install dgl -f https://data.dgl.ai/eheels/repo.html

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in links: https://data.dgl.ai/eheels/repo.html


In [3]:
!pip install dglgo -f https://data.dgl.ai/eheels/repo.html

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in links: https://data.dgl.ai/eheels/repo.html
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.5/63.5 kB 3.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.2/91.2 kB 5.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.2/45.2 kB 7.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.4/52.4 kB 7.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 109.1/109.1 kB 14.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.8/78.8 kB 10.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 29.4/29.4 MB 42.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.3/41.3 kB 5.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 118.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 485.6/485.6 kB 60.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
 

In [4]:
%matplotlib inline
import os
os.environ["DGLBACKEND"]="pytorch"
import dgl
import numpy as np
import torch
import torch.nn as nn

##Querying graph structure

dgl.DGLGraph.num_nodesdgl.

We define a graph g using the dgl.graph function. The dgl.graph function takes two lists as its arguments: the first list contains the source nodes of the edges and the second list contains the destination nodes of the edges. In this case, we define a graph with five nodes and four edges.

We then call the num_nodes method of g to get the number of nodes in the graph. This method returns an integer representing the number of nodes in the graph, which we store in the variable num_nodes.

Finally, we print the value of num_nodes to the console



In [5]:
g = dgl.heterograph({
    ('user', 'follows', 'user'): (torch.tensor([0, 1]), torch.tensor([1, 2])),
    ('user', 'plays', 'game'): (torch.tensor([3, 4]), torch.tensor([5, 6]))
})

In [6]:
g.num_nodes('user')
g.num_nodes('game')
g.num_nodes()

12

dgl.DGLGraph.num_nodes


The num_edges method of dgl.DGLGraph returns the number of edges

The dgl.graph function takes two lists as its arguments: the first list contains the source nodes of the edges and the second list contains the destination nodes of the edges. In this case, we define a graph with five nodes and four edges.

We then call the num_edges method of g to get the number of edges in the graph. This method returns an integer representing the number of edges in the graph, which we store in the variable num_edges.

Finally, we print the value of num_edges to the console

In [7]:
g = dgl.heterograph({
    ('user', 'follows', 'user'): (torch.tensor([0, 1]), torch.tensor([1, 2])),
    ('user', 'follows', 'game'): (torch.tensor([0, 1, 2]), torch.tensor([1, 2, 3])),
    ('user', 'plays', 'game'): (torch.tensor([1, 3]), torch.tensor([2, 3]))
})

In [8]:
g.num_edges('plays')
g.num_edges()

7

In [9]:
g.num_edges(('user', 'follows', 'user'))
g.num_edges(('user', 'follows', 'game'))

3

dgl.DGLGraph.num_src_nodes

The num_src_nodes method of dgl.DGLGraph returns the number of source nodes in a graph. 

We call the num_src_nodes method of g to get the number of source nodes in the graph. This method returns an integer representing the number of source nodes in the graph, which we store in the variable num_src_nodes.
we print the value of num_src_nodes to the console.

In [10]:
g = dgl.graph((torch.tensor([0, 1]), torch.tensor([1, 2])))
g.num_src_nodes()

3

In [11]:
g = dgl.heterograph({
    ('developer', 'develops', 'game'): (torch.tensor([0, 1]), torch.tensor([1, 2])),
    ('user', 'plays', 'game'): (torch.tensor([3, 4]), torch.tensor([5, 6]))
})

In [12]:
g.num_src_nodes('developer')
g.num_src_nodes('user')
g.num_src_nodes()

7

dgl.DGLGraph.num_dst_nodes
The num_dst_nodes method of dgl.DGLGraph returns the number of destination nodes in a graph. 


We then call the num_dst_nodes method of g to get the number of destination nodes in the graph. This method returns an integer representing the number of destination nodes in the graph, which we store in the variable num_dst_nodes.
 we print the value of num_dst_nodes to the console
this code demonstrates how to use the num_dst_nodes method of dgl.DGLGraph to get the number of destination nodes in a graph.

In [13]:
g = dgl.graph((torch.tensor([0, 1]), torch.tensor([1, 2])))
g.num_dst_nodes()

3

In [14]:
g = dgl.heterograph({
    ('user', 'follows', 'user'): (torch.tensor([0, 1]), torch.tensor([1, 2])),
    ('user', 'plays', 'game'): (torch.tensor([3, 4]), torch.tensor([5, 6]))
})

In [15]:
g.num_dst_nodes('user')
g.num_dst_nodes('game')
g.num_dst_nodes()

12

dgl.DGLGraph.is_multigraph
The is_multigraph method of dgl.DGLGraph returns a boolean indicating whether the graph is a multigraph or not. 

 call the is_multigraph method of g to check if the graph is a multigraph. This method returns a boolean value, True if the graph is a multigraph and False otherwise. In this case, since we have only one edge between each pair of nodes, the graph is not a multigraph, and the value of is_multigraph should be False.


In [16]:
g = dgl.graph((torch.tensor([0, 1]), torch.tensor([1, 3])))
g.is_multigraph
g = dgl.graph((torch.tensor([0, 1, 1]), torch.tensor([1, 3, 3])))
g.is_multigraph

True

In [17]:
g = dgl.heterograph({
    ('user', 'follows', 'user'): (torch.tensor([0, 1]), torch.tensor([1, 2])),
    ('user', 'follows', 'game'): (torch.tensor([0, 1, 2]), torch.tensor([1, 2, 3]))
})
g.is_multigraph
g = dgl.heterograph({
    ('user', 'follows', 'user'): (torch.tensor([0, 1, 1]), torch.tensor([1, 2, 2])),
    ('user', 'follows', 'game'): (torch.tensor([0, 1, 2]), torch.tensor([1, 2, 3]))
})
g.is_multigraph

True

dgl.DGLGraph.is_homogeneous

The is_homogeneous method of dgl.DGLGraph returns a boolean indicating whether the graph is homogeneous or not.

call the is_homogeneous method of g1 and g2 to check if the graphs are homogeneous. This method returns a boolean value, True if the graph is homogeneous and False otherwise.

respectively.

Overall, this code demonstrates how to use the is_homogeneous method of dgl.DGLGraph to check whether a graph is homogeneous or not.

In [18]:
g = dgl.graph((torch.tensor([0, 0, 1, 1]), torch.tensor([1, 0, 2, 3])))
g.is_homogeneous

True

In [19]:
g = dgl.heterograph({
    ('user', 'follows', 'game'): (torch.tensor([0, 1, 2]), torch.tensor([1, 2, 3]))})
g.is_homogeneous

False

dgl.DGLGraph.has_nodes
The has_nodes method of dgl.DGLGraph returns a boolean indicating whether the graph has the specified nodes or not

In [20]:
g = dgl.heterograph({
    ('user', 'follows', 'user'): (torch.tensor([0, 1]), torch.tensor([1, 2])),
    ('user', 'plays', 'game'): (torch.tensor([3, 4]), torch.tensor([0, 1]))
})

In [21]:
g.has_nodes(0, 'user')
g.has_nodes(3, 'game')
g.has_nodes(torch.tensor([3, 0, 1]), 'game')

tensor([False,  True,  True])

dgl.DGLGraph.has_edges_between

The has_edges_between method of dgl.DGLGraph returns a boolean indicating whether the graph has edges between the specified source and destination nodes or not.

In [22]:
g = dgl.graph((torch.tensor([0, 0, 1, 1]), torch.tensor([1, 0, 2, 3])))

In [23]:
g.has_edges_between(1, 2)
g.has_edges_between(torch.tensor([1, 2]), torch.tensor([2, 3]))

tensor([ True, False])

In [24]:
g = dgl.heterograph({
    ('user', 'follows', 'user'): (torch.tensor([0, 1]), torch.tensor([1, 2])),
    ('user', 'follows', 'game'): (torch.tensor([0, 1, 2]), torch.tensor([1, 2, 3])),
    ('user', 'plays', 'game'): (torch.tensor([1, 3]), torch.tensor([2, 3]))
})
g.has_edges_between(torch.tensor([1, 2]), torch.tensor([2, 3]), 'plays')

tensor([ True, False])

In [25]:
g.has_edges_between(torch.tensor([1, 2]), torch.tensor([2, 3]),
                    ('user', 'follows', 'user'))
g.has_edges_between(torch.tensor([1, 2]), torch.tensor([2, 3]),
                    ('user', 'follows', 'game'))

tensor([True, True])

dgl.DGLGraph.predecessors
The predecessors method of dgl.DGLGraph returns the predecessors of the specified nodes in the graph. 

In [26]:
g = dgl.graph((torch.tensor([0, 0, 1, 1]), torch.tensor([1, 1, 2, 3])))

In [27]:
g.predecessors(1)

tensor([0, 0])

In [28]:
hg = dgl.heterograph({
    ('user', 'follows', 'user'): (torch.tensor([0, 1]), torch.tensor([1, 2])),
    ('user', 'plays', 'game'): (torch.tensor([3, 4]), torch.tensor([5, 6]))
})
hg.predecessors(1, etype='follows')

tensor([0])

dgl.DGLGraph.successors

The successors method of dgl.DGLGraph returns the successors of the specified nodes in the graph. 

In [29]:
g = dgl.graph((torch.tensor([0, 0, 1, 1]), torch.tensor([1, 1, 2, 3])))

In [30]:
g.successors(1)

tensor([2, 3])

In [31]:
hg = dgl.heterograph({
    ('user', 'follows', 'user'): (torch.tensor([0, 1]), torch.tensor([1, 2])),
    ('user', 'plays', 'game'): (torch.tensor([3, 4]), torch.tensor([5, 6]))
})
hg.successors(1, etype='follows')

tensor([2])

dgl.DGLGraph.edge_ids

The edge_ids method of dgl.DGLGraph returns the edge IDs of the edges between the specified source and destination nodes in the graph

In [32]:
g = dgl.graph((torch.tensor([0, 0, 1, 1, 1]), torch.tensor([1, 0, 2, 3, 2])))

In [33]:
g.edge_ids(0, 0)
g.edge_ids(torch.tensor([1, 0]), torch.tensor([3, 1]))

tensor([3, 0])

In [34]:
g.edge_ids(torch.tensor([1, 0]), torch.tensor([3, 1]), return_uv=True)

(tensor([1, 0]), tensor([3, 1]), tensor([3, 0]))

In [35]:
g = dgl.heterograph({
    ('user', 'follows', 'user'): (torch.tensor([0, 1]), torch.tensor([1, 2])),
    ('user', 'follows', 'game'): (torch.tensor([0, 1, 2]), torch.tensor([1, 2, 3])),
    ('user', 'plays', 'game'): (torch.tensor([1, 3]), torch.tensor([2, 3]))
})
g.edge_ids(torch.tensor([1]), torch.tensor([2]), etype='plays')

tensor([0])

In [36]:
g.edge_ids(torch.tensor([0, 1]), torch.tensor([1, 2]),
           etype=('user', 'follows', 'user'))
g.edge_ids(torch.tensor([1, 2]), torch.tensor([2, 3]),
           etype=('user', 'follows', 'game'))

tensor([1, 2])

dgl.DGLGraph.find_edges

The find_edges method of dgl.DGLGraph returns the source and destination nodes of the edges with the specified edge IDs in the graph.

In [37]:
g = dgl.graph((torch.tensor([0, 0, 1, 1]), torch.tensor([1, 0, 2, 3])))

In [38]:
g.find_edges(torch.tensor([0, 2]))

(tensor([0, 1]), tensor([1, 2]))

In [39]:
hg = dgl.heterograph({
    ('user', 'follows', 'user'): (torch.tensor([0, 1]), torch.tensor([1, 2])),
    ('user', 'plays', 'game'): (torch.tensor([3, 4]), torch.tensor([5, 6]))
})
hg.find_edges(torch.tensor([1, 0]), 'plays')

(tensor([4, 3]), tensor([6, 5]))

dgl.DGLGraph.in_edges

The in_edges method of dgl.DGLGraph returns the source and destination nodes of the edges that point to the specified destination nodes in the graph.

In [40]:
g = dgl.graph((torch.tensor([0, 0, 1, 1]), torch.tensor([1, 0, 2, 3])))

In [41]:
g.in_edges(torch.tensor([1, 0]))

(tensor([0, 0]), tensor([1, 0]))

In [42]:
g.in_edges(torch.tensor([1, 0]), form='all')

(tensor([0, 0]), tensor([1, 0]), tensor([0, 1]))

In [43]:
hg = dgl.heterograph({
    ('user', 'follows', 'user'): (torch.tensor([0, 1]), torch.tensor([1, 2])),
    ('user', 'plays', 'game'): (torch.tensor([3, 4]), torch.tensor([5, 6]))
})
hg.in_edges(torch.tensor([1, 0]), etype='follows')

(tensor([0]), tensor([1]))

DGLGraph.out_edge

The out_edges method of dgl.DGLGraph returns the source and destination nodes of the edges that originate from the specified source nodes in the graph.

In [44]:
g.out_edges(torch.tensor([1, 2]))

(tensor([1, 1]), tensor([2, 3]))

In [45]:
g.out_edges(torch.tensor([1, 2]), form='all')

(tensor([1, 1]), tensor([2, 3]), tensor([2, 3]))

In [46]:
hg = dgl.heterograph({
    ('user', 'follows', 'user'): (torch.tensor([0, 1]), torch.tensor([1, 2])),
    ('user', 'plays', 'game'): (torch.tensor([3, 4]), torch.tensor([5, 6]))
})
hg.out_edges(torch.tensor([1, 2]), etype='follows')

(tensor([1]), tensor([2]))

DGLGraph.in_degrees

he in_degrees method of dgl.DGLGraph returns the number of incoming edges to the specified nodes in the graph. 

In [47]:
g = dgl.graph((torch.tensor([0, 0, 1, 1]), torch.tensor([1, 1, 2, 3])))

In [48]:
g.in_degrees()

tensor([0, 2, 1, 1])

In [49]:
g.in_degrees(torch.tensor([1, 2]))

tensor([2, 1])

In [50]:
hg = dgl.heterograph({
    ('user', 'follows', 'user'): (torch.tensor([0, 1]), torch.tensor([1, 2])),
    ('user', 'plays', 'game'): (torch.tensor([3, 4]), torch.tensor([5, 6]))
})
hg.in_degrees(torch.tensor([1, 0]), etype='follows')

tensor([1, 0])

DGLGraph.out_degrees

The out_degrees method of dgl.DGLGraph returns the number of outgoing edges from the specified nodes in the graph. call the out_degrees method of g to get the number of outgoing edges from the specified nodes. This method takes a tensor of node IDs as its argument and returns a tensor of out-degrees, which represents the number of outgoing edges from each specified node.

In [51]:
g = dgl.graph((torch.tensor([0, 0, 1, 1]), torch.tensor([1, 1, 2, 3])))

In [52]:
g.out_degrees()

tensor([2, 2, 0, 0])

In [53]:
g.out_degrees(torch.tensor([1, 2]))

tensor([2, 0])

In [54]:
hg = dgl.heterograph({
    ('user', 'follows', 'user'): (torch.tensor([0, 1]), torch.tensor([1, 2])),
    ('user', 'plays', 'game'): (torch.tensor([3, 4]), torch.tensor([5, 6]))
})
hg.out_degrees(torch.tensor([1, 0]), etype='follows')

tensor([1, 1])

##Querying and manipulating node/edge ID type

dgl.DGLGraph.idtype

The idtype attribute of dgl.DGLGraph returns the data type of the node and edge IDs used by the graph.
this code demonstrates how to use the idtype attribute of dgl.DGLGraph to find the data type of the node and edge IDs used by a graph.

In [55]:
src_ids = torch.tensor([0, 0, 1])
dst_ids = torch.tensor([1, 2, 2])
g = dgl.graph((src_ids, dst_ids))
g.idtype
g = dgl.graph((src_ids, dst_ids), idtype=torch.int32)
g.idtype

torch.int32

dgl.DGLGraph.long

The long method of dgl.DGLGraph returns a new graph with the node and edge IDs converted to 32-bit integers.
 this code demonstrates how to use the long method of dgl.DGLGraph to convert the node and edge IDs of a graph to 32-bit integers.

In [56]:
# (0, 1), (0, 2), (1, 2)
g = dgl.graph((torch.tensor([0, 0, 1]).int(), torch.tensor([1, 2, 2]).int()))
g.ndata['feat'] = torch.ones(3, 1)
g.idtype

torch.int32

In [57]:
# A cloned graph with an idtype of int64
g_long = g.long()
g_long.idtype
# The idtype of the original graph does not change.
g.idtype
g_long.edges()
g_long.ndata

{'feat': tensor([[1.],
        [1.],
        [1.]])}

dgl.DGLGraph.int

The int method of dgl.DGLGraph returns a new graph with the node and edge IDs converted to 64-bit integers

In [58]:
# (0, 1), (0, 2), (1, 2)
g = dgl.graph((torch.tensor([0, 0, 1]), torch.tensor([1, 2, 2])))
g.ndata['feat'] = torch.ones(3, 1)
g.idtype

torch.int64

In [59]:
# A cloned graph with an idtype of int32
g_int = g.int()
g_int.idtype
# The idtype of the original graph does not change.
g.idtype
g_int.edges()
g_int.ndata

{'feat': tensor([[1.],
        [1.],
        [1.]])}

##Using Node/edge features

dgl.DGLGraph.nodes



The nodes method of dgl.DGLGraph returns a NodeView object that represents the set of nodes in the graph.
his code demonstrates how to use the nodes method of dgl.DGLGraph to get the set of nodes in a graph, which is returned as a NodeView object that can be used to index into the graph's node features.

In [60]:
g = dgl.graph((torch.tensor([0, 1]), torch.tensor([1, 2])))
hg = dgl.heterograph({
    ('user', 'follows', 'user'): (torch.tensor([0, 1]), torch.tensor([1, 2])),
    ('user', 'plays', 'game'): (torch.tensor([3, 4]), torch.tensor([5, 6]))
})

In [61]:
g.nodes()

tensor([0, 1, 2])

In [62]:
hg.nodes('user')

tensor([0, 1, 2, 3, 4])

In [63]:
hg.nodes['user'].data['h'] = torch.ones(5, 1)
hg.nodes['user'].data['h']

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.]])

dgl.DGLGraph.ndata

The ndata method of dgl.DGLGraph returns the feature data associated with the nodes in the graph.
this code demonstrates how to use the ndata method of dgl.DGLGraph to get the feature data associated with the nodes of a graph. In this case, we add random node features to the graph using PyTorch's torch.randn function and retrieve the 'x' feature data of all nodes using the ndata met

In [64]:
g = dgl.graph((torch.tensor([0, 1]), torch.tensor([1, 2])))
g.ndata['h'] = torch.ones(3, 1)
g.ndata['h']

tensor([[1.],
        [1.],
        [1.]])

In [65]:
g = dgl.heterograph({
    ('user', 'follows', 'user'): (torch.tensor([1, 2]), torch.tensor([3, 4])),
    ('player', 'plays', 'game'): (torch.tensor([2, 2]), torch.tensor([1, 1]))
})
g.ndata['h'] = {'game': torch.zeros(2, 1), 'player': torch.ones(3, 1)}
g.ndata['h']
g.ndata['h'] = {'game': torch.ones(2, 1)}
g.ndata['h']

{'game': tensor([[1.],
         [1.]]),
 'player': tensor([[1.],
         [1.],
         [1.]])}

dgl.DGLGraph.edges

 this code demonstrates how to use the edges method of dgl.DGLGraph to get the set of edges in a graph, which is returned as a tuple of two tensors that represent the source and destination nodes of the edges.

In [66]:
g = dgl.heterograph({
    ('user', 'follows', 'user'): (torch.tensor([1, 2]), torch.tensor([3, 4])),
    ('player', 'plays', 'game'): (torch.tensor([2, 2]), torch.tensor([1, 1]))
})

In [67]:
g.ndata['h'] = {'game': torch.zeros(2, 1), 'player': torch.ones(3, 1)}
g.ndata['h']

{'game': tensor([[0.],
         [0.]]),
 'player': tensor([[1.],
         [1.],
         [1.]])}

In [68]:
g.ndata['h'] = {'game': torch.ones(2, 1)}
g.ndata['h']

{'game': tensor([[1.],
         [1.]]),
 'player': tensor([[1.],
         [1.],
         [1.]])}

In [69]:
g = dgl.graph((torch.tensor([1, 0, 0]), torch.tensor([1, 1, 0])))
g.edges()

(tensor([1, 0, 0]), tensor([1, 1, 0]))

In [70]:
g.edges(form='all', order='srcdst')

(tensor([0, 0, 1]), tensor([0, 1, 1]), tensor([2, 1, 0]))

In [71]:
hg = dgl.heterograph({
    ('user', 'follows', 'user'): (torch.tensor([0, 1]), torch.tensor([1, 2])),
    ('user', 'plays', 'game'): (torch.tensor([3, 4]), torch.tensor([5, 6]))
})
hg.edges(etype='plays')

(tensor([3, 4]), tensor([5, 6]))

In [72]:
hg = dgl.heterograph({
    ('user', 'follows', 'user'): (torch.tensor([0, 1]), torch.tensor([1, 2])),
    ('user', 'plays', 'game'): (torch.tensor([3, 4]), torch.tensor([5, 6]))
})

In [73]:
hg.edges['follows'].data['h'] = torch.ones(2, 1)
hg.edges['follows'].data['h']

tensor([[1.],
        [1.]])

dgl.DGLGraph.edata

The edata method of dgl.DGLGraph returns the feature data associated with the edges in the graph.

In [74]:
g = dgl.graph((torch.tensor([0, 1]), torch.tensor([1, 2])))
g.edata['h'] = torch.ones(2, 1)
g.edata['h']

tensor([[1.],
        [1.]])

In [75]:
g = dgl.heterograph({
    ('user', 'follows', 'user'): (torch.tensor([1, 2]), torch.tensor([3, 4])),
    ('user', 'plays', 'user'): (torch.tensor([2, 2]), torch.tensor([1, 1])),
    ('player', 'plays', 'game'): (torch.tensor([2, 2]), torch.tensor([1, 1]))
})
g.edata['h'] = {('user', 'follows', 'user'): torch.zeros(2, 1),
                ('user', 'plays', 'user'): torch.ones(2, 1)}
g.edata['h']
g.edata['h'] = {('user', 'follows', 'user'): torch.ones(2, 1)}
g.edata['h']

{('user',
  'follows',
  'user'): tensor([[1.],
         [1.]]),
 ('user',
  'plays',
  'user'): tensor([[1.],
         [1.]])}

dgl.DGLGraph.node_attr_schemes

The node_attr_schemes attribute of dgl.DGLGraph returns a dictionary that contains the data type and shape of the node features in the graph


In [76]:
g = dgl.graph((torch.tensor([0, 1]), torch.tensor([1, 2])))
g.ndata['h1'] = torch.randn(3, 1)
g.ndata['h2'] = torch.randn(3, 2)
g.node_attr_schemes()

{'h1': Scheme(shape=(1,), dtype=torch.float32),
 'h2': Scheme(shape=(2,), dtype=torch.float32)}

dgl.DGLGraph.edge_attr_schemes

The edge_attr_schemes attribute of dgl.DGLGraph returns a dictionary that contains the data type and shape of the edge features in the graph.

In [77]:
g = dgl.heterograph({('user', 'plays', 'game'):
                     (torch.tensor([1, 2]), torch.tensor([3, 4]))})
g.nodes['user'].data['h1'] = torch.randn(3, 1)
g.nodes['user'].data['h2'] = torch.randn(3, 2)
g.node_attr_schemes('user')

{'h1': Scheme(shape=(1,), dtype=torch.float32),
 'h2': Scheme(shape=(2,), dtype=torch.float32)}

In [78]:
g = dgl.graph((torch.tensor([0, 1]), torch.tensor([1, 2])))
g.edata['h1'] = torch.randn(2, 1)
g.edata['h2'] = torch.randn(2, 2)
g.edge_attr_schemes()

{'h1': Scheme(shape=(1,), dtype=torch.float32),
 'h2': Scheme(shape=(2,), dtype=torch.float32)}

In [79]:
g = dgl.heterograph({('user', 'plays', 'game'):
                     (torch.tensor([1, 2]), torch.tensor([3, 4])),
                     ('user', 'follows', 'user'):
                     (torch.tensor([3, 4]), torch.tensor([5, 6]))})
g.edges['plays'].data['h1'] = torch.randn(2, 1)
g.edges['plays'].data['h2'] = torch.randn(2, 2)
g.edge_attr_schemes('plays')

{'h1': Scheme(shape=(1,), dtype=torch.float32),
 'h2': Scheme(shape=(2,), dtype=torch.float32)}

dgl.DGLGraph.srcnodes
The srcnodes method of dgl.DGLGraph returns the source nodes of the edges in the graph as a tensor. 

In [80]:
g = dgl.heterograph({
    ('user', 'plays', 'game'): (torch.tensor([0]), torch.tensor([1])),
    ('developer', 'develops', 'game'): (torch.tensor([1]), torch.tensor([2]))
})

In [81]:
g.srcnodes('user')
g.srcnodes('developer')

tensor([0, 1])

In [82]:
g.srcnodes['user'].data['h'] = torch.ones(1, 1)
g.srcnodes['user'].data['h']

tensor([[1.]])

In [83]:
g = dgl.heterograph({
    ('user', 'follows', 'user'): (torch.tensor([0]), torch.tensor([1])),
    ('developer', 'develops', 'game'): (torch.tensor([1]), torch.tensor([2]))
})

In [84]:
g.srcnodes('game')

tensor([0, 1, 2])

In [85]:
g.srcnodes['game'].data['h'] = torch.ones(3, 1)
g.srcnodes['game'].data['h']

tensor([[1.],
        [1.],
        [1.]])

dgl.DGLGraph.dstnodes

The dstnodes method of dgl.DGLGraph returns the destination nodes of the edges in the graph as a tensor

In [86]:
g = dgl.heterograph({
    ('user', 'plays', 'game'): (torch.tensor([0]), torch.tensor([1])),
    ('developer', 'develops', 'game'): (torch.tensor([1]), torch.tensor([2]))
})

In [87]:
g.dstnodes['game'].data['h'] = torch.ones(3, 1)
g.dstnodes['game'].data['h']

tensor([[1.],
        [1.],
        [1.]])

In [88]:
g.dstnodes('game')

tensor([0, 1, 2])

In [89]:
g = dgl.heterograph({
    ('user', 'follows', 'user'): (torch.tensor([0]), torch.tensor([1])),
    ('developer', 'develops', 'game'): (torch.tensor([1]), torch.tensor([2]))
})

In [90]:
g.dstnodes('developer')

tensor([0, 1])

In [91]:
g.dstnodes['developer'].data['h'] = torch.ones(2, 1)
g.dstnodes['developer'].data['h']

tensor([[1.],
        [1.]])

dgl.DGLGraph.srcdata

The srcdata method of dgl.DGLGraph returns the feature data associated with the source nodes of the edges in the graph.

In [92]:
g = dgl.heterograph({
    ('user', 'plays', 'game'): (torch.tensor([0, 1]), torch.tensor([1, 2]))})
g.srcdata['h'] = torch.ones(2, 1)
g.srcdata['h']

tensor([[1.],
        [1.]])

In [93]:
g = dgl.heterograph({
    ('user', 'plays', 'game'): (torch.tensor([1, 2]), torch.tensor([3, 4])),
    ('player', 'plays', 'game'): (torch.tensor([2, 2]), torch.tensor([1, 1]))
})
g.srcdata['h'] = {'user': torch.zeros(3, 1), 'player': torch.ones(3, 1)}
g.srcdata['h']
g.srcdata['h'] = {'user': torch.ones(3, 1)}
g.srcdata['h']

{'player': tensor([[1.],
         [1.],
         [1.]]),
 'user': tensor([[1.],
         [1.],
         [1.]])}

dgl.DGLGraph.dstdata

The dstdata method of dgl.DGLGraph returns the feature data associated with the destination nodes of the edges in the graph.

In [94]:
g = dgl.heterograph({
    ('user', 'plays', 'game'): (torch.tensor([0, 1]), torch.tensor([1, 2]))})
g.dstdata['h'] = torch.ones(3, 1)
g.dstdata['h']

tensor([[1.],
        [1.],
        [1.]])

In [95]:
g = dgl.heterograph({
    ('user', 'plays', 'game'): (torch.tensor([1, 2]), torch.tensor([1, 2])),
    ('user', 'watches', 'movie'): (torch.tensor([2, 2]), torch.tensor([1, 1]))
})
g.dstdata['h'] = {'game': torch.zeros(3, 1), 'movie': torch.ones(2, 1)}
g.dstdata['h']

{'game': tensor([[0.],
         [0.],
         [0.]]),
 'movie': tensor([[1.],
         [1.]])}

In [96]:
g = dgl.heterograph({
    ('user', 'plays', 'game'): (torch.tensor([1, 2]), torch.tensor([1, 2])),
    ('user', 'watches', 'movie'): (torch.tensor([2, 2]), torch.tensor([1, 1]))
})
g.dstdata['h'] = {'game': torch.zeros(3, 1), 'movie': torch.ones(2, 1)}
g.dstdata['h']
g.dstdata['h'] = {'game': torch.ones(3, 1)}
g.dstdata['h']

{'game': tensor([[1.],
         [1.],
         [1.]]),
 'movie': tensor([[1.],
         [1.]])}

##Transforming graph

dgl.node_subgraph

The dgl.node_subgraph function in DGL (Deep Graph Library) is used to create a subgraph consisting of a specified set of nodes and all the edges that connect them. The function takes in the following arguments:

g: The input graph from which the subgraph is to be extracted.
nodes: A list or tensor of node IDs that specifies the nodes in the subgraph.
readonly: A boolean value that specifies if the subgraph should be read-only (default is True).
ntype: A string specifying the node type of the input graph that should be used to create the subgraph (default is None).
etype: A string or a tuple of strings specifying the edge types of the input graph that should be used to create the subgraph (default is None).
store_ids: A boolean value that specifies if the node and edge IDs of the subgraph should be stored in the subgraph (default is True).
The function returns a subgraph that contains all the edges of the input graph that connect the specified nodes. The subgraph is a DGLGraph object that supports many of the same operations as the input graph, but only contains the nodes and edges that are part of the subgraph.


In [97]:
g = dgl.graph(([0, 1, 2, 3, 4], [1, 2, 3, 4, 0]))  # 5-node cycle
sg = dgl.node_subgraph(g, [0, 1, 4])
sg
sg.edges()
sg.ndata[dgl.NID]  # original node IDs
sg.edata[dgl.EID]  # original edge IDs

tensor([0, 4])

In [98]:
nodes = torch.tensor([True, True, False, False, True])  # choose nodes [0, 1, 4]
dgl.node_subgraph(g, nodes)

Graph(num_nodes=3, num_edges=2,
      ndata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64)}
      edata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64)})

In [99]:
g.ndata['x'] = torch.arange(10).view(5, 2)
sg = dgl.node_subgraph(g, [0, 1, 4])
sg
sg.ndata['x']

tensor([[0, 1],
        [2, 3],
        [8, 9]])

In [100]:
g = dgl.heterograph({
    ('user', 'plays', 'game'): ([0, 1, 1, 2], [0, 0, 2, 1]),
    ('user', 'follows', 'user'): ([0, 1, 1], [1, 2, 2])
})
sub_g = dgl.node_subgraph(g, {'user': [1, 2]})
sub_g

Graph(num_nodes={'game': 0, 'user': 2},
      num_edges={('user', 'follows', 'user'): 2, ('user', 'plays', 'game'): 0},
      metagraph=[('user', 'user', 'follows'), ('user', 'game', 'plays')])

dgl.edge_subgraph

he dgl.edge_subgraph function in DGL (Deep Graph Library) is used to create a subgraph consisting of a specified set of edges and the nodes that are connected by those edges. The function takes in the following arguments:

g: The input graph from which the subgraph is to be extracted.
edges: A list or tensor of edge IDs that specifies the edges in the subgraph.
readonly: A boolean value that specifies if the subgraph should be read-only (default is True).
store_ids: A boolean value that specifies if the node and edge IDs of the subgraph should be stored in the subgraph (default is True).
The function returns a subgraph that contains the specified edges and all the nodes that are connected by those edges. The subgraph is a DGLGraph object that supports many of the same operations as the input graph, but only contains the nodes and edges that are part of the subgraph.
 the subgraph is created as a view of the input graph, which means that any changes made to the subgraph will be reflected in the input graph as well.

In [101]:
g = dgl.graph(([0, 1, 2, 3, 4], [1, 2, 3, 4, 0]))  # 5-node cycle
sg = dgl.edge_subgraph(g, [0, 4])
sg
sg.edges()
sg.ndata[dgl.NID]  # original node IDs
sg.edata[dgl.EID]  # original edge IDs

tensor([0, 4])

In [102]:
sg = dgl.edge_subgraph(g, [0, 4], relabel_nodes=False)
sg
sg.edges()

(tensor([0, 4]), tensor([1, 0]))

In [103]:
nodes = torch.tensor([True, False, False, False, True])  # choose edges [0, 4]
dgl.edge_subgraph(g, nodes)

Graph(num_nodes=3, num_edges=2,
      ndata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64)}
      edata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64)})

In [104]:
g.ndata['x'] = torch.arange(10).view(5, 2)
sg = dgl.edge_subgraph(g, [0, 4])
sg
sg.ndata[dgl.NID]
sg.ndata['x']

tensor([[0, 1],
        [8, 9],
        [2, 3]])

In [105]:
g = dgl.heterograph({
    ('user', 'plays', 'game'): ([0, 1, 1, 2], [0, 0, 2, 1]),
    ('user', 'follows', 'user'): ([0, 1, 1], [1, 2, 2])
})
sub_g = dgl.edge_subgraph(g, {('user', 'follows', 'user'): [1, 2],
                              ('user', 'plays', 'game'): [2]})
print(sub_g)

Graph(num_nodes={'game': 1, 'user': 2},
      num_edges={('user', 'follows', 'user'): 2, ('user', 'plays', 'game'): 1},
      metagraph=[('user', 'user', 'follows'), ('user', 'game', 'plays')])


dgl.node_type_subgraph

the  dgl.node_type_subgraph function in DGL (Deep Graph Library) is used to create a subgraph consisting of nodes of a specified node type and all the edges that connect them. The function takes in the following arguments:

g: The input graph from which the subgraph is to be extracted.
ntype: A string specifying the node type of the input graph that should be used to create the subgraph.
readonly: A boolean value that specifies if the subgraph should be read-only (default is True).
store_ids: A boolean value that specifies if the node and edge IDs of the subgraph should be stored in the subgraph (default is True).
The function returns a subgraph that contains all the edges of the input graph that connect nodes of the specified type. The subgraph is a DGLGraph object that supports many of the same operations as the input graph, but only contains the nodes and edges that are part of the subgraph.

In [106]:
g = dgl.heterograph({
    ('user', 'plays', 'game'): ([0, 1, 1, 2], [0, 0, 2, 1]),
    ('user', 'follows', 'user'): ([0, 1, 1], [1, 2, 2])
})
# Set node features
g.nodes['user'].data['h'] = torch.tensor([[0.], [1.], [2.]])

In [107]:
sub_g = g.node_type_subgraph(['user'])
print(sub_g)

Graph(num_nodes=3, num_edges=3,
      ndata_schemes={'h': Scheme(shape=(1,), dtype=torch.float32)}
      edata_schemes={})


In [108]:
sub_g.nodes['user'].data['h']

tensor([[0.],
        [1.],
        [2.]])

dgl.edge_type_subgraph

In [109]:
g = dgl.heterograph({
    ('user', 'plays', 'game'): ([0, 1, 1, 2], [0, 0, 2, 1]),
    ('user', 'follows', 'user'): ([0, 1, 1], [1, 2, 2])
})
# Set edge features
g.edges['follows'].data['h'] = torch.tensor([[0.], [1.], [2.]])

In [110]:
sub_g = g.edge_type_subgraph(['follows'])
sub_g

Graph(num_nodes=3, num_edges=3,
      ndata_schemes={}
      edata_schemes={'h': Scheme(shape=(1,), dtype=torch.float32)})

In [111]:
sub_g.edges['follows'].data['h']

tensor([[0.],
        [1.],
        [2.]])

dgl.DGLGraph.__getitem__

The __getitem__ method in DGL (Deep Graph Library) is used to access nodes or edges of a graph using indexing syntax. This method allows you to select a subset of the nodes or edges from a graph by specifying their IDs or indices.

In [112]:
g = dgl.heterograph({
    ('A1', 'AB1', 'B'): ([0, 1, 2], [1, 2, 3]),
    ('A1', 'AB2', 'B'): ([1, 2, 3], [3, 4, 5]),
    ('A2', 'AB2', 'B'): ([1, 3, 5], [2, 4, 6])})
new_g = g['A1', :, 'B']         # combines all edge types between A1 and B
new_g
new_g.edges()
new_g2 = g[:, 'AB2', 'B']        # combines all node types that are source of AB2
new_g2
new_g2.edges()

(tensor([1, 2, 3, 5, 7, 9]), tensor([3, 4, 5, 2, 4, 6]))

In [113]:
g = dgl.heterograph({
    ('A1', 'AB1', 'B'): ([0, 1, 2], [1, 2, 3]),
    ('A1', 'AB2', 'B'): ([1, 2, 3], [3, 4, 5]),
    ('A2', 'AB2', 'B'): ([1, 3, 5], [2, 4, 6])})
new_g1 = g['A1', :, 'B']         # combines all edge types between A1 and B
new_g1
new_g.edges()
new_g2 = g[:, 'AB2', 'B']        # combines all node types that are source of AB2
new_g2
new_g2.edges()

(tensor([1, 2, 3, 5, 7, 9]), tensor([3, 4, 5, 2, 4, 6]))

In [114]:
new_g1.edges['AB1+AB2'].data[dgl.EID]


tensor([0, 1, 2, 0, 1, 2])

In [115]:
new_g1.edges['AB1+AB2'].data[dgl.ETYPE]

tensor([0, 0, 0, 1, 1, 1])

In [116]:

new_g2.nodes['A1+A2'].data[dgl.NID]


tensor([0, 1, 2, 3, 0, 1, 2, 3, 4, 5])

In [117]:
new_g2.nodes['A1+A2'].data[dgl.NTYPE]

tensor([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [118]:
import dgl
g = dgl.graph(([0, 1, 2, 3, 4, 0, 1, 2, 3, 4], [1, 2, 3, 4, 0, 4, 0, 1, 2, 3]))
dgl.laplacian_lambda_max(g)

[1.8090169943749477]

In [119]:
import dgl
g = dgl.graph(([0,1,2,3,4,0,1,2,3,4], [0,1,2,3,4,1,2,3,4,0]))
dgl.khop_graph(g, 1)
dgl.khop_graph(g, 3)

Graph(num_nodes=5, num_edges=40,
      ndata_schemes={}
      edata_schemes={})

dgl.line_graph

The dgl.line_graph function in DGL (Deep Graph Library) is used to create a new graph where the nodes represent edges in the original graph and edges represent connections between those edges. The function takes in the following arguments:

g: The input graph from which the line graph is to be created.
backtracking: A boolean value that specifies if backtracking edges should be added to the line graph (default is False).
shared: A boolean value that specifies if the node and edge features of the input graph should be shared by the line graph (default is False).
The function returns a new graph that represents the line graph of the input graph. The nodes of the line graph are the edges of the input graph, and the edges of the line graph represent connections between those edges in the original graph.


In [120]:
A = [[0, 0, 1],
     [1, 0, 1],
     [1, 1, 0]]

In [121]:
# g = dgl.graph(([0, 1, 1, 2, 2],[2, 0, 2, 0, 1]), 'user', 'follows')
# lg = g.line_graph()
# lg
# lg.edges()
# lg = g.line_graph(backtracking=False)
# lg
# lg.edges()

In [122]:
import dgl

g = dgl.graph(([0, 1, 1, 2, 2], [2, 0, 2, 0, 1]))
lg = g.line_graph()
print(lg.edges())

lg = g.line_graph(backtracking=False)
print(lg.edges())

(tensor([0, 0, 1, 2, 2, 3, 4, 4]), tensor([3, 4, 0, 3, 4, 0, 1, 2]))
(tensor([0, 1, 2, 4]), tensor([4, 0, 3, 1]))


dgl.reverse

The dgl.reverse function in DGL (Deep Graph Library) is used to reverse the direction of all edges in a given graph. The function takes in the following arguments:

g: The input graph to be reversed.
The function returns a new graph that is the reverse of the input graph, with all edges pointing in the opposite direction.

In [123]:
import dgl
import torch as th
g = dgl.graph((th.tensor([0, 1, 2]), th.tensor([1, 2, 0])))
g.ndata['h'] = th.tensor([[0.], [1.], [2.]])
g.edata['h'] = th.tensor([[3.], [4.], [5.]])

In [124]:
rg = dgl.reverse(g, copy_edata=True)
rg.ndata['h']

tensor([[0.],
        [1.],
        [2.]])

In [125]:
rg.edges()
rg.edata['h']

tensor([[3.],
        [4.],
        [5.]])

In [126]:
g = dgl.heterograph({
    ('user', 'follows', 'user'): (th.tensor([0, 2]), th.tensor([1, 2])),
    ('user', 'plays', 'game'): (th.tensor([1, 2, 1]), th.tensor([2, 1, 1]))
})
g.nodes['game'].data['hv'] = th.ones(3, 1)
g.edges['plays'].data['he'] = th.zeros(3, 1)

In [127]:
rg = dgl.reverse(g, copy_ndata=True)
rg
rg.edges(etype='follows')
rg.edges(etype='plays')
rg.nodes['game'].data['hv']
rg.edges['plays'].data

{}

dgl.add_self_loop

The dgl.add_self_loop function in DGL (Deep Graph Library) is used to add self-loops to a given graph. A self-loop is an edge that connects a node to itself.

The function takes in the following arguments:

g: The input graph to which self-loops are to be added.
etid: An optional integer or a list of integers specifying the edge type IDs of the self-loops to be added (default is None, which adds self-loops for all edge types in the graph).
The function modifies the input graph by adding self-loops to it. If the input graph already contains self-loops, the function adds additional self-loops on top of them.

In [128]:
g = dgl.graph((torch.tensor([0, 0, 2]), torch.tensor([2, 1, 0])))
g.ndata['hv'] = torch.arange(3).float().reshape(-1, 1)
g.edata['he'] = torch.arange(3).float().reshape(-1, 1)
g = dgl.add_self_loop(g, fill_data='sum')
g
g.edata['he']

/usr/local/lib/python3.10/dist-packages/dgl/backend/pytorch/tensor.py:449: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  assert input.numel() == input.storage().size(), (


tensor([[0.],
        [1.],
        [2.],
        [2.],
        [1.],
        [0.]])

In [129]:
g = dgl.heterograph({
    ('user', 'follows', 'user'): (torch.tensor([1, 2]),
                                  torch.tensor([0, 1])),
    ('user', 'plays', 'game'): (torch.tensor([0, 1]),
                                torch.tensor([0, 1]))})
g = dgl.add_self_loop(g, etype='follows')
g

Graph(num_nodes={'game': 2, 'user': 3},
      num_edges={('user', 'follows', 'user'): 5, ('user', 'plays', 'game'): 2},
      metagraph=[('user', 'user', 'follows'), ('user', 'game', 'plays')])

dgl.remove_self_loop

The dgl.remove_self_loop function in DGL (Deep Graph Library) is used to remove self-loops from a given graph. A self-loop is an edge that connects a node to itself.

The function takes in the following arguments:

g: The input graph from which self-loops are to be removed.
etid: An optional integer or a list of integers specifying the edge type IDs of the self-loops to be removed (default is None, which removes self-loops for all edge types in the graph).
The function modifies the input graph by removing self-loops from it. If the input graph does not contain any self-loops, the function does not modify the graph.

In [130]:
g = dgl.graph((torch.tensor([0, 0, 0, 1]), torch.tensor([1, 0, 0, 2])))
g.edata['he'] = torch.arange(4).float().reshape(-1, 1)
g = dgl.remove_self_loop(g)
g
g.edata['he']

tensor([[0.],
        [3.]])

In [131]:
g = dgl.heterograph({
    ('user', 'follows', 'user'): (torch.tensor([0, 1, 1, 1, 2]),
                                  torch.tensor([0, 0, 1, 1, 1])),
    ('user', 'plays', 'game'): (torch.tensor([0, 1]),
                                torch.tensor([0, 1]))
    })
g = dgl.remove_self_loop(g, etype='follows')
g.num_nodes('user')
g.num_nodes('game')
g.num_edges('follows')
g.num_edges('plays')

2

dgl.to_simple

The dgl.to_simple function in DGL (Deep Graph Library) is used to convert a given graph to a simple graph, which is a graph that does not contain multiple edges between the same pair of nodes or self-loops.

The function takes in the following arguments:

g: The input graph to be converted to a simple graph.
The function returns a new graph that is a simple version of the input graph, with multiple edges between the same pair of nodes and self-loops removed.

In [132]:
import dgl
import torch as th
g = dgl.graph((th.tensor([0, 1, 2, 1]), th.tensor([1, 2, 0, 2])))
g.ndata['h'] = th.tensor([[0.], [1.], [2.]])
g.edata['h'] = th.tensor([[3.], [4.], [5.], [6.]])

In [133]:
sg, wm = dgl.to_simple(g, return_counts='cnt', writeback_mapping=True)
sg.ndata['h']
u, v, eid = sg.edges(form='all')
u
v
eid
sg.edata['cnt']
wm
'h' in g.edata

True

In [134]:
g = dgl.heterograph({
    ('user', 'wins', 'user'): (th.tensor([0, 2, 0, 2, 2]), th.tensor([1, 1, 2, 1, 0])),
    ('user', 'plays', 'game'): (th.tensor([1, 2, 1]), th.tensor([2, 1, 1]))
})
g.nodes['game'].data['hv'] = th.ones(3, 1)
g.edges['plays'].data['he'] = th.zeros(3, 1)

In [135]:
sg, wm = dgl.to_simple(g, copy_ndata=False, writeback_mapping=True)
sg
sg.edges(etype='wins')
wm[('user', 'wins', 'user')]
sg.edges(etype='plays')
wm[('user', 'plays', 'game')]
'hv' in sg.nodes['game'].data
'he' in sg.edges['plays'].data
sg.edata['count']

{('user', 'plays', 'game'): tensor([1, 1, 1]),
 ('user', 'wins', 'user'): tensor([1, 1, 1, 2])}

dgl.DGLGraph.to_cugraph

The to_cugraph function in DGL (Deep Graph Library) is used to convert a DGLGraph object to a CuGraph object. CuGraph is a graph analytics library that runs on NVIDIA GPUs and provides a set of graph algorithms that can be used to analyze large graphs efficiently.

The to_cugraph function takes no arguments and returns a new CuGraph object that represents the same graph as the DGLGraph object.

In [136]:
import os
os.environ['PATH'] += ":/usr/local/bin"

In [137]:
!pip install cugraph

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Preparing metadata (setup.py) ... done
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cugraph
  Running setup.py clean for cugraph
Failed to build cugraph
ERROR: Could not build wheels for cugraph, which is required to install pyproject.toml-based projects


In [138]:
!pip install cugraph-cpu

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
ERROR: Could not find a version that satisfies the requirement cugraph-cpu (from versions: none)
ERROR: No matching distribution found for cugraph-cpu


In [139]:
import dgl
import cugraph
import torch

ModuleNotFoundError: ignored

In [ ]:
g = dgl.graph((torch.tensor([1, 2]), torch.tensor([1, 3]))).to('cuda')
cugraph_g = g.to_cugraph()
cugraph_g.edges()

dgl.reorder_graph

The dgl.reorder_graph function in DGL (Deep Graph Library) is used to reorder the nodes of a given graph according to a new node ordering. This can be useful, for example, when the nodes in the graph have some inherent ordering that is not reflected in their IDs, and we want to reorder the nodes to better reflect this underlying structure.

The function takes in the following arguments:

g: The input graph to be reordered.
new_order: A list or a tensor of node IDs specifying the new ordering of nodes in the graph.
The function returns a new graph that is a copy of the input graph, but with the nodes reordered according to the new ordering.

In [141]:
import dgl
import torch
g = dgl.graph((torch.tensor([0, 1, 2, 3, 4]), torch.tensor([2, 2, 3, 2, 3])))
g.ndata['h'] = torch.arange(g.num_nodes() * 2).view(g.num_nodes(), 2)
g.edata['w'] = torch.arange(g.num_edges() * 1).view(g.num_edges(), 1)
g.ndata
g.edata

{'w': tensor([[0],
        [1],
        [2],
        [3],
        [4]])}

In [142]:
rg = dgl.reorder_graph(g, node_permute_algo='rcmk')
rg.ndata
rg.edata

{'w': tensor([[4],
        [3],
        [1],
        [2],
        [0]]), '_ID': tensor([4, 3, 1, 2, 0])}

In [145]:
rg = dgl.reorder_graph(g, node_permute_algo='metis', permute_config={'k':2})
rg.ndata
rg.edata

Convert a graph into a bidirected graph: 0.000 seconds, peak memory: 3.685 GB
Construct multi-constraint weights: 0.000 seconds, peak memory: 3.685 GB
Metis partitioning: 0.000 seconds, peak memory: 3.685 GB


{'w': tensor([[3],
        [4],
        [0],
        [1],
        [2]]), '_ID': tensor([3, 4, 0, 1, 2])}

In [144]:
rg = dgl.reorder_graph(g, node_permute_algo='custom',
                       permute_config={'nodes_perm': [3, 2, 0, 4, 1]})
rg.ndata
rg.edata

{'w': tensor([[3],
        [2],
        [0],
        [4],
        [1]]), '_ID': tensor([3, 2, 0, 4, 1])}

In [143]:
rg = dgl.reorder_graph(g, node_permute_algo='rcmk', edge_permute_algo='dst')
print(rg.ndata)
print(rg.edata)

{'h': tensor([[8, 9],
        [6, 7],
        [2, 3],
        [4, 5],
        [0, 1]]), '_ID': tensor([4, 3, 1, 2, 0])}
{'w': tensor([[4],
        [2],
        [3],
        [1],
        [0]]), '_ID': tensor([4, 2, 3, 1, 0])}


In [146]:
rg = dgl.reorder_graph(g, edge_permute_algo='custom',
                       permute_config={'edges_perm': [1, 2, 3, 4, 0]})
print(rg.ndata)
print(rg.edata)

{'h': tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]), '_ID': tensor([0, 1, 2, 3, 4])}
{'w': tensor([[1],
        [2],
        [3],
        [4],
        [0]]), '_ID': tensor([1, 2, 3, 4, 0])}


##Subgraph Extraction Ops

dgl.node_subgraph

The dgl.node_subgraph function in DGL (Deep Graph Library) is used to extract a subgraph of a given graph that contains only a specified set of nodes (and their incident edges).

The function takes in the following arguments:

g: The input graph from which the subgraph is to be extracted.
nodes: A list or a tensor of node IDs specifying the nodes to be included in the subgraph.
The function returns a new graph that is a subgraph of the input graph, containing only the specified nodes and their incident edges.

In [147]:
g = dgl.graph(([0, 1, 2, 3, 4], [1, 2, 3, 4, 0]))  # 5-node cycle
sg = dgl.node_subgraph(g, [0, 1, 4])
sg
sg.edges()
sg.ndata[dgl.NID]  # original node IDs
sg.edata[dgl.EID]  # original edge IDs

tensor([0, 4])

In [148]:
nodes = torch.tensor([True, True, False, False, True])  # choose nodes [0, 1, 4]
dgl.node_subgraph(g, nodes)

Graph(num_nodes=3, num_edges=2,
      ndata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64)}
      edata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64)})

In [149]:
g.ndata['x'] = torch.arange(10).view(5, 2)
sg = dgl.node_subgraph(g, [0, 1, 4])
sg
sg.ndata['x']

tensor([[0, 1],
        [2, 3],
        [8, 9]])

In [150]:
g = dgl.heterograph({
    ('user', 'plays', 'game'): ([0, 1, 1, 2], [0, 0, 2, 1]),
    ('user', 'follows', 'user'): ([0, 1, 1], [1, 2, 2])
})
sub_g = dgl.node_subgraph(g, {'user': [1, 2]})
sub_g

Graph(num_nodes={'game': 0, 'user': 2},
      num_edges={('user', 'follows', 'user'): 2, ('user', 'plays', 'game'): 0},
      metagraph=[('user', 'user', 'follows'), ('user', 'game', 'plays')])

dgl.edge_subgraph

The dgl.edge_subgraph function in DGL (Deep Graph Library) is used to extract a subgraph of a given graph that contains only a specified set of edges (and their incident nodes).

The function takes in the following arguments:

g: The input graph from which the subgraph is to be extracted.
edges: A pair of lists or tensors (u, v) specifying the source and destination nodes of the edges to be included in the subgraph.
The function returns a new graph that is a subgraph of the input graph, containing only the specified edges and their incident nodes.

In [151]:
g = dgl.graph(([0, 1, 2, 3, 4], [1, 2, 3, 4, 0]))  # 5-node cycle
sg = dgl.edge_subgraph(g, [0, 4])
sg
sg.edges()
sg.ndata[dgl.NID]  # original node IDs
sg.edata[dgl.EID]  # original edge IDs

tensor([0, 4])

In [152]:
sg = dgl.edge_subgraph(g, [0, 4], relabel_nodes=False)
sg
sg.edges()

(tensor([0, 4]), tensor([1, 0]))

In [153]:
nodes = torch.tensor([True, False, False, False, True])  # choose edges [0, 4]
dgl.edge_subgraph(g, nodes)

Graph(num_nodes=3, num_edges=2,
      ndata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64)}
      edata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64)})

In [154]:
g.ndata['x'] = torch.arange(10).view(5, 2)
sg = dgl.edge_subgraph(g, [0, 4])
sg
sg.ndata[dgl.NID]
sg.ndata['x']

tensor([[0, 1],
        [8, 9],
        [2, 3]])

In [155]:
g = dgl.heterograph({
    ('user', 'plays', 'game'): ([0, 1, 1, 2], [0, 0, 2, 1]),
    ('user', 'follows', 'user'): ([0, 1, 1], [1, 2, 2])
})
sub_g = dgl.edge_subgraph(g, {('user', 'follows', 'user'): [1, 2],
                              ('user', 'plays', 'game'): [2]})
print(sub_g)

Graph(num_nodes={'game': 1, 'user': 2},
      num_edges={('user', 'follows', 'user'): 2, ('user', 'plays', 'game'): 1},
      metagraph=[('user', 'user', 'follows'), ('user', 'game', 'plays')])


dgl.node_type_subgraph

The dgl.node_type_subgraph function in DGL (Deep Graph Library) is used to extract a subgraph of a given bipartite graph that contains only the nodes and edges of a specified node type.

The function takes in the following arguments:

g: The input bipartite graph from which the subgraph is to be extracted.
ntype: The string name of the node type to be included in the subgraph.
The function returns a new graph that is a subgraph of the input bipartite graph, containing only the nodes and edges of the specified node type.

In [156]:
g = dgl.heterograph({
    ('user', 'plays', 'game'): ([0, 1, 1, 2], [0, 0, 2, 1]),
    ('user', 'follows', 'user'): ([0, 1, 1], [1, 2, 2])
})
# Set node features
g.nodes['user'].data['h'] = torch.tensor([[0.], [1.], [2.]])

In [157]:
sub_g = g.node_type_subgraph(['user'])
print(sub_g)

Graph(num_nodes=3, num_edges=3,
      ndata_schemes={'h': Scheme(shape=(1,), dtype=torch.float32)}
      edata_schemes={})


In [158]:
sub_g.nodes['user'].data['h']

tensor([[0.],
        [1.],
        [2.]])

dgl.edge_type_subgraph

The dgl.edge_type_subgraph function in DGL (Deep Graph Library) is used to extract a subgraph of a given bipartite graph that contains only the edges of a specified edge type.

The function takes in the following arguments:

g: The input bipartite graph from which the subgraph is to be extracted.
etype: The string name of the edge type to be included in the subgraph.
The function returns a new graph that is a subgraph of the input bipartite graph, containing only the edges of the specified edge type.

In [159]:
g = dgl.heterograph({
    ('user', 'plays', 'game'): ([0, 1, 1, 2], [0, 0, 2, 1]),
    ('user', 'follows', 'user'): ([0, 1, 1], [1, 2, 2])
})
# Set edge features
g.edges['follows'].data['h'] = torch.tensor([[0.], [1.], [2.]])

In [160]:
sub_g = g.edge_type_subgraph(['follows'])
sub_g

Graph(num_nodes=3, num_edges=3,
      ndata_schemes={}
      edata_schemes={'h': Scheme(shape=(1,), dtype=torch.float32)})

In [161]:
sub_g.edges['follows'].data['h']

tensor([[0.],
        [1.],
        [2.]])

dgl.in_subgraph

he dgl.in_subgraph function in DGL (Deep Graph Library) is used to determine whether a given edge is in a specified subgraph.

The function takes in the following arguments:

g: The input graph that contains the edge.
subg: The subgraph that is to be checked for the presence of the edge.
eid: The ID of the edge to be checked.
The function returns a Boolean value that is True if the edge is in the subgraph, and False otherwise.

In [162]:
g = dgl.graph(([0, 1, 2, 3, 4], [1, 2, 3, 4, 0]))  # 5-node cycle
g.edata['w'] = torch.arange(10).view(5, 2)
sg = dgl.in_subgraph(g, [2, 0])
sg
sg.edges()
sg.edata[dgl.EID]  # original edge IDs
sg.edata['w']  # also extract the features

tensor([[2, 3],
        [8, 9]])

In [163]:
sg = dgl.in_subgraph(g, [2, 0], relabel_nodes=True)
sg
sg.edges()
sg.edata[dgl.EID]  # original edge IDs
sg.ndata[dgl.NID]  # original node IDs

tensor([1, 4, 2, 0])

In [164]:
g = dgl.heterograph({
    ('user', 'plays', 'game'): ([0, 1, 1, 2], [0, 0, 2, 1]),
    ('user', 'follows', 'user'): ([0, 1, 1], [1, 2, 2])})
sub_g = g.in_subgraph({'user': [2], 'game': [2]})
sub_g

Graph(num_nodes={'game': 3, 'user': 3},
      num_edges={('user', 'follows', 'user'): 2, ('user', 'plays', 'game'): 1},
      metagraph=[('user', 'user', 'follows'), ('user', 'game', 'plays')])

dgl.out_subgraph

The dgl.out_subgraph function in DGL (Deep Graph Library) is used to extract a subgraph of a given graph that contains only the edges that originate from a specified set of nodes.

The function takes in the following arguments:

g: The input graph from which the subgraph is to be extracted.
nodes: A list or a tensor of node IDs specifying the nodes whose outgoing edges are to be included in the subgraph.
The function returns a new graph that is a subgraph of the input graph, containing only the edges that originate from the specified nodes and their destination nodes.

In [165]:
g = dgl.graph(([0, 1, 2, 3, 4], [1, 2, 3, 4, 0]))  # 5-node cycle
g.edata['w'] = torch.arange(10).view(5, 2)
sg = dgl.out_subgraph(g, [2, 0])
sg
sg.edges()
sg.edata[dgl.EID]  # original edge IDs
sg.edata['w']  # also extract the features

tensor([[4, 5],
        [0, 1]])

In [166]:
sg = dgl.out_subgraph(g, [2, 0], relabel_nodes=True)
sg
sg.edges()
sg.edata[dgl.EID]  # original edge IDs
sg.ndata[dgl.NID]  # original node IDs

tensor([2, 0, 3, 1])

In [167]:
g = dgl.heterograph({
    ('user', 'plays', 'game'): ([0, 1, 1, 2], [0, 0, 2, 1]),
    ('user', 'follows', 'user'): ([0, 1, 1], [1, 2, 2])})
sub_g = g.out_subgraph({'user': [1]})
sub_g

Graph(num_nodes={'game': 3, 'user': 3},
      num_edges={('user', 'follows', 'user'): 2, ('user', 'plays', 'game'): 2},
      metagraph=[('user', 'user', 'follows'), ('user', 'game', 'plays')])

dgl.khop_in_subgraph

The dgl.khop_in_subgraph function in DGL (Deep Graph Library) is used to extract a subgraph of a given graph that contains only the edges that are k hops away from a specified set of nodes.

The function takes in the following arguments:

g: The input graph from which the subgraph is to be extracted.
k: The number of hops to consider when extracting the subgraph.
nodes: A list or a tensor of node IDs specifying the nodes from which to compute the k-hop subgraph.
The function returns a new graph that is a subgraph of the input graph, containing only the edges that are k hops away from the specified nodes and their destination nodes.

In [168]:
g = dgl.graph(([1, 1, 2, 3, 4], [0, 2, 0, 4, 2]))
g.edata['w'] = torch.arange(10).view(5, 2)
sg, inverse_indices = dgl.khop_in_subgraph(g, 0, k=2)
sg
sg.edges()
sg.edata[dgl.EID]  # original edge IDs
sg.edata['w']  # also extract the features
inverse_indices

tensor([0])

In [169]:
g = dgl.heterograph({
    ('user', 'plays', 'game'): ([0, 1, 1, 2], [0, 0, 2, 1]),
    ('user', 'follows', 'user'): ([0, 1, 1], [1, 2, 2])})
sg, inverse_indices = dgl.khop_in_subgraph(g, {'game': 0}, k=2)
sg
inverse_indices

{'game': tensor([0])}

dgl.khop_out_subgraph

The dgl.khop_out_subgraph function in DGL (Deep Graph Library) is used to extract a subgraph of a given graph that contains only the edges that are k hops away from a specified set of nodes.

The function takes in the following arguments:

g: The input graph from which the subgraph is to be extracted.
k: The number of hops to consider when extracting the subgraph.
nodes: A list or a tensor of node IDs specifying the nodes whose outgoing edges are to be included in the subgraph.
The function returns a new graph that is a subgraph of the input graph, containing only the edges that are k hops away from the specified nodes and their destination nodes.

In [170]:
g = dgl.graph(([0, 2, 0, 4, 2], [1, 1, 2, 3, 4]))
g.edata['w'] = torch.arange(10).view(5, 2)
sg, inverse_indices = dgl.khop_out_subgraph(g, 0, k=2)
sg
sg.edges()
sg.edata[dgl.EID]  # original edge IDs
sg.edata['w']  # also extract the features
inverse_indices

tensor([0])

In [171]:
g = dgl.heterograph({
    ('user', 'plays', 'game'): ([0, 1, 1, 2], [0, 0, 2, 1]),
    ('user', 'follows', 'user'): ([0, 1], [1, 3])})
sg, inverse_indices = dgl.khop_out_subgraph(g, {'user': 0}, k=2)
sg
inverse_indices

{'user': tensor([0])}

##save and load

In [183]:
import dgl
import torch as th

In [172]:
g1 = dgl.graph(([0, 1, 2], [1, 2, 3]))
g2 = dgl.graph(([0, 2], [2, 3]))
g2.edata["e"] = th.ones(2, 4)

In [173]:
g1 = dgl.graph(([0, 1, 2], [1, 2, 3]))
g2 = dgl.graph(([0, 2], [2, 3]))
g2.edata["e"] = th.ones(2, 4)

In [174]:
from dgl.data.utils import save_graphs
graph_labels = {"glabel": th.tensor([0, 1])}
save_graphs("./data.bin", [g1, g2], graph_labels)

In [175]:
from dgl.data.utils import save_graphs
graph_labels = {"glabel": th.tensor([0, 1])}
save_graphs("./data.bin", [g1, g2], graph_labels)

In [184]:
from dgl.data.utils import load_graphs
glist = load_graphs("./data.bin")
     

In [177]:
from dgl.data.utils import load_graphs
glist, label_dict = load_graphs("./data.bin") # glist will be [g1, g2]
glist, label_dict = load_graphs("./data.bin", [0]) # glist will be [g1]

In [176]:
import dgl
import torch

# Define the graph
g = dgl.graph(([0, 0, 1], [1, 2, 2]))  # a small example graph

# Define the node and edge features
g.ndata['feat'] = torch.randn((3, 5))
g.edata['feat'] = torch.randn((3, 4))


In [178]:
g1 = dgl.heterograph({
('user', 'follows', 'user'): (torch.tensor([0, 1]), torch.tensor([1, 2])),
('user', 'plays', 'game'): (torch.tensor([3, 4]), torch.tensor([5, 6]))
})

g2 = dgl.graph((torch.tensor([0, 1]), torch.tensor([1, 2])))

g3 = dgl.graph((torch.tensor([0, 1]), torch.tensor([1, 3])))

g4 = dgl.graph((torch.tensor([0, 1, 1]), torch.tensor([1, 3, 3])))

g5 = dgl.heterograph({
('user', 'follows', 'user'): (torch.tensor([0, 1]), torch.tensor([1, 2])),
('user', 'follows', 'game'): (torch.tensor([0, 1, 2]), torch.tensor([1, 2, 3]))
})

g6 = dgl.heterograph({
('user', 'follows', 'user'): (torch.tensor([0, 1, 1]), torch.tensor([1, 2, 2])),
('user', 'follows', 'game'): (torch.tensor([0, 1, 2]), torch.tensor([1, 2, 3]))
})

g7 = dgl.graph((torch.tensor([0, 0, 1, 1]), torch.tensor([1, 0, 2, 3])))

g8 = dgl.heterograph({
('user', 'follows', 'game'): (torch.tensor([0, 1, 2]), torch.tensor([1, 2, 3]))
})

g9 = dgl.heterograph({
('user', 'follows', 'user'): (torch.tensor([0, 1]), torch.tensor([1, 2])),
('user', 'plays', 'game'): (torch.tensor([3, 4]), torch.tensor([0, 1]))
})

g10 = dgl.graph((torch.tensor([0, 0, 1, 1]), torch.tensor([1, 0, 2, 3])))

g11 = dgl.heterograph({
('user', 'follows', 'user'): (torch.tensor([0, 1]), torch.tensor([1, 2])),
('user', 'follows', 'game'): (torch.tensor([0, 1, 2]), torch.tensor([1, 2, 3])),
('user', 'plays', 'game'): (torch.tensor([1, 3]), torch.tensor([2, 3]))
})

g12 = dgl.graph((torch.tensor([0, 0, 1, 1]), torch.tensor([1, 1, 2, 3])))

hg = dgl.heterograph({
('user', 'follows', 'user'): (torch.tensor([0, 1]), torch.tensor([1, 2])),
('user', 'plays', 'game'): (torch.tensor([3, 4]), torch.tensor([5, 6]))
})

g13 = dgl.graph((torch.tensor([0, 0, 1, 1]), torch.tensor([1, 1, 2, 3])))

hg1 = dgl.heterograph({
('user', 'follows', 'user'): (torch.tensor([0, 1]), torch.tensor([1, 2])),
('user', 'follows', 'game'): (torch.tensor([0, 1, 2]), torch.tensor([1, 2, 3])),
('user', 'plays', 'game'): (torch.tensor([1, 3]), torch.tensor([2, 3]))
})

In [179]:
import dgl
import torch

# Define the first graph
g1 = dgl.heterograph({
    ('user', 'follows', 'user'): (torch.tensor([0, 1]), torch.tensor([1, 2])),
    ('user', 'follows', 'game'): (torch.tensor([0, 1, 2]), torch.tensor([1, 2, 3]))
})

# Define the second graph
g2 = dgl.heterograph({
    ('user', 'follows', 'user'): (torch.tensor([0, 1, 1]), torch.tensor([1, 2, 2])),
    ('user', 'follows', 'game'): (torch.tensor([0, 1, 2]), torch.tensor([1, 2, 3]))
})

# Save the graphs to a file
dgl.save_graphs("my_graphs.dgl", [g1, g2])

# Load the graphs from the file
loaded_graphs, _ = dgl.load_graphs("my_graphs.dgl")

# Print the number of nodes and edges in the loadedgraphs
for g in loaded_graphs:
    print(g.number_of_nodes(), g.number_of_edges(), g.is_multigraph)

7 5 False
7 6 True


In [180]:
# Save the graphs to a file
dgl.save_graphs("my_graphs.dgl", [g1, g2,g3,g4,g5,g6,g7,g8,g9,g10,g11,g12,hg,g13,hg1])

# Load the graphs from the file
loaded_graphs, _ = dgl.load_graphs("my_graphs.dgl")

# Print the number of nodes and edges in the loadedgraphs
for g in loaded_graphs:
    print(g.number_of_nodes(), g.number_of_edges(), g.is_multigraph)

7 5 False
7 6 True
4 2 False
4 3 True
7 5 False
7 6 True
4 4 False
7 3 False
7 4 False
4 4 False
8 7 False
4 4 True
12 4 False
4 4 True
8 7 False


In [181]:

# Define a graph
g = dgl.graph(([0, 0, 1, 2, 3], [1, 2, 2, 3, 4]))
g.ndata['feat'] = torch.randn(5, 10)

# Save the graph to a file
dgl.save_graphs("my_graph.dgl", [g])

# Load the graph from the file
loaded_graphs, _ = dgl.load_graphs("my_graph.dgl")  # Notice the underscore after loaded_graphs

# Extract the loaded graph from the list
loaded_g = loaded_graphs[0]

# Print the node features of the loaded graph
print(loaded_g.ndata['feat'])


tensor([[ 1.1082, -0.9110,  1.3411,  0.8355, -1.0578,  1.6094, -0.2940,  0.8327,
          0.2752, -1.6009],
        [ 0.7197, -0.4006,  0.2726,  0.1478, -0.8890,  0.7049,  1.5787, -0.8344,
          1.0508,  1.4462],
        [ 0.2773, -0.0376,  0.4835,  1.9549,  0.9225,  1.7706, -0.4106, -0.9792,
         -0.0941,  0.8314],
        [-0.9997, -0.9379,  0.4298, -0.8325,  0.0914,  0.2311, -0.9339, -0.5585,
          1.4100,  2.0270],
        [-1.4659, -1.7837, -0.7701, -0.1043,  0.0674,  1.3184,  0.9651, -0.8088,
         -0.4963,  0.4001]])


In [182]:
import dgl
import torch

# Define the first graph
g1 = dgl.heterograph({
    ('user', 'follows', 'user'): (torch.tensor([0, 1]), torch.tensor([1, 2])),
    ('user', 'follows', 'game'): (torch.tensor([0, 1, 2]), torch.tensor([1, 2, 3]))
})

# Define the second graph
g2 = dgl.heterograph({
    ('user', 'follows', 'user'): (torch.tensor([0, 1, 1]), torch.tensor([1, 2, 2])),
    ('user', 'follows', 'game'): (torch.tensor([0, 1, 2]), torch.tensor([1, 2, 3]))
})

# Save the graphs to a file
dgl.save_graphs("my_graphs.dgl", [g1, g2])

# Load the graphs from the file
loaded_graphs, _ = dgl.load_graphs("my_graphs.dgl")

# Print the number of nodes and edges in the loadedgraphs
for g in loaded_graphs:
    print(g.number_of_nodes(), g.number_of_edges(), g.is_multigraph)

7 5 False
7 6 True


In [ ]:
# Return the subgraph induced by k-hop out-neighborhood of the specified node(s).
h = dgl.graph((torch.tensor([0, 0, 1, 1]), torch.tensor([1, 0, 2, 3])))
sh = h.khop_out_subgraph(0, k=2) ##??
     

from dgl.data.utils import save_graphs
save_graphs("./data.bin", [g, h])
     

from dgl.data.utils import load_graphs
glist = load_graphs("./data.bin")

##1

In [ ]:
g = dgl.heterograph({
    ('user', 'plays', 'game'): (torch.tensor([0, 1]), torch.tensor([1, 2]))})
g.srcdata['h'] = torch.ones(2, 1)
g.srcdata['h']

In [ ]:
g = dgl.heterograph({
    ('user', 'plays', 'game'): (torch.tensor([1, 2]), torch.tensor([3, 4])),
    ('player', 'plays', 'game'): (torch.tensor([2, 2]), torch.tensor([1, 1]))
})
g.srcdata['h'] = {'user': torch.zeros(3, 1), 'player': torch.ones(3, 1)}
g.srcdata['h']
g.srcdata['h'] = {'user': torch.ones(3, 1)}
g.srcdata['h']

In [ ]:
g = dgl.heterograph({
    ('user', 'plays', 'game'): (torch.tensor([0, 1]), torch.tensor([1, 2]))})
g.dstdata['h'] = torch.ones(3, 1)
g.dstdata['h']

In [ ]:
g = dgl.heterograph({
    ('user', 'plays', 'game'): (torch.tensor([1, 2]), torch.tensor([1, 2])),
    ('user', 'watches', 'movie'): (torch.tensor([2, 2]), torch.tensor([1, 1]))
})
g.dstdata['h'] = {'game': torch.zeros(3, 1), 'movie': torch.ones(2, 1)}
g.dstdata['h']
g.dstdata['h'] = {'game': torch.ones(3, 1)}
g.dstdata['h']

In [ ]:
g = dgl.graph(([0, 1, 2, 3, 4], [1, 2, 3, 4, 0]))  # 5-node cycle
sg = dgl.edge_subgraph(g, [0, 4])
sg
sg.edges()
sg.ndata[dgl.NID]  # original node IDs
sg.edata[dgl.EID]  # original edge IDs

In [ ]:
sg = dgl.edge_subgraph(g, [0, 4], relabel_nodes=False)
sg
sg.edges()

In [ ]:
nodes = torch.tensor([True, False, False, False, True])  # choose edges [0, 4]
dgl.edge_subgraph(g, nodes)

In [ ]:
g.ndata['x'] = torch.arange(10).view(5, 2)
sg = dgl.edge_subgraph(g, [0, 4])
sg
sg.ndata[dgl.NID]
sg.ndata['x']

In [ ]:
g = dgl.heterograph({
    ('user', 'plays', 'game'): ([0, 1, 1, 2], [0, 0, 2, 1]),
    ('user', 'follows', 'user'): ([0, 1, 1], [1, 2, 2])
})
sub_g = dgl.edge_subgraph(g, {('user', 'follows', 'user'): [1, 2],
                              ('user', 'plays', 'game'): [2]})
print(sub_g)

In [ ]:
g = dgl.heterograph({
    ('user', 'plays', 'game'): ([0, 1, 1, 2], [0, 0, 2, 1]),
    ('user', 'follows', 'user'): ([0, 1, 1], [1, 2, 2])
})
# Set node features
g.nodes['user'].data['h'] = torch.tensor([[0.], [1.], [2.]])

In [ ]:
sub_g = g.node_type_subgraph(['user'])
print(sub_g)

In [ ]:
sub_g.nodes['user'].data['h']

In [ ]:
g = dgl.heterograph({
    ('user', 'plays', 'game'): ([0, 1, 1, 2], [0, 0, 2, 1]),
    ('user', 'follows', 'user'): ([0, 1, 1], [1, 2, 2])
})
# Set edge features
g.edges['follows'].data['h'] = torch.tensor([[0.], [1.], [2.]])

In [ ]:
sub_g = g.edge_type_subgraph(['follows'])
sub_g

In [ ]:
sub_g.edges['follows'].data['h']

In [ ]:
g = dgl.graph(([0, 1, 2, 3, 4], [1, 2, 3, 4, 0]))  # 5-node cycle
g.edata['w'] = torch.arange(10).view(5, 2)
sg = dgl.in_subgraph(g, [2, 0])
sg
sg.edges()
sg.edata[dgl.EID]  # original edge IDs
sg.edata['w']  # also extract the features

In [ ]:
sg = dgl.in_subgraph(g, [2, 0], relabel_nodes=True)
sg
sg.edges()
sg.edata[dgl.EID]  # original edge IDs
sg.ndata[dgl.NID]  # original node IDs

In [ ]:
g = dgl.heterograph({
    ('user', 'plays', 'game'): ([0, 1, 1, 2], [0, 0, 2, 1]),
    ('user', 'follows', 'user'): ([0, 1, 1], [1, 2, 2])})
sub_g = g.in_subgraph({'user': [2], 'game': [2]})
sub_g

In [ ]:
g = dgl.graph(([0, 1, 2, 3, 4], [1, 2, 3, 4, 0]))  # 5-node cycle
g.edata['w'] = torch.arange(10).view(5, 2)
sg = dgl.out_subgraph(g, [2, 0])
sg
sg.edges()
sg.edata[dgl.EID]  # original edge IDs
sg.edata['w']  # also extract the features

In [ ]:
sg = dgl.out_subgraph(g, [2, 0], relabel_nodes=True)
sg
sg.edges()
sg.edata[dgl.EID]  # original edge IDs
sg.ndata[dgl.NID]  # original node IDs

In [ ]:
g = dgl.heterograph({
    ('user', 'plays', 'game'): ([0, 1, 1, 2], [0, 0, 2, 1]),
    ('user', 'follows', 'user'): ([0, 1, 1], [1, 2, 2])})
sub_g = g.out_subgraph({'user': [1]})
sub_g

In [ ]:
g = dgl.graph(([1, 1, 2, 3, 4], [0, 2, 0, 4, 2]))
g.edata['w'] = torch.arange(10).view(5, 2)
sg, inverse_indices = dgl.khop_in_subgraph(g, 0, k=2)
sg
sg.edges()
sg.edata[dgl.EID]  # original edge IDs
sg.edata['w']  # also extract the features
inverse_indices

In [ ]:
g = dgl.heterograph({
    ('user', 'plays', 'game'): ([0, 1, 1, 2], [0, 0, 2, 1]),
    ('user', 'follows', 'user'): ([0, 1, 1], [1, 2, 2])})
sg, inverse_indices = dgl.khop_in_subgraph(g, {'game': 0}, k=2)
sg
inverse_indices

In [ ]:
g = dgl.graph(([0, 2, 0, 4, 2], [1, 1, 2, 3, 4]))
g.edata['w'] = torch.arange(10).view(5, 2)
sg, inverse_indices = dgl.khop_out_subgraph(g, 0, k=2)
sg
sg.edges()
sg.edata[dgl.EID]  # original edge IDs
sg.edata['w']  # also extract the features
inverse_indices

In [ ]:
g = dgl.heterograph({
    ('user', 'plays', 'game'): ([0, 1, 1, 2], [0, 0, 2, 1]),
    ('user', 'follows', 'user'): ([0, 1], [1, 3])})
sg, inverse_indices = dgl.khop_out_subgraph(g, {'user': 0}, k=2)
sg
inverse_indices

In [ ]:
g = dgl.graph((torch.tensor([0, 1]), torch.tensor([1, 2])))
g.num_edges()
g = dgl.add_edges(g, torch.tensor([1, 3]), torch.tensor([0, 1]))
g.num_edges()

In [ ]:
g.num_nodes()

In [ ]:
g.edata['h'] = torch.ones(4, 1)
g = dgl.add_edges(g, torch.tensor([1]), torch.tensor([1]))
g.edata['h']

In [ ]:
g = dgl.add_edges(g, torch.tensor([0, 0]), torch.tensor([2, 2]),
                  {'h': torch.tensor([[1.], [2.]]), 'w': torch.ones(2, 1)})
g.edata['h']

In [ ]:
g.edata['w']

In [ ]:
g = dgl.heterograph({
    ('user', 'plays', 'game'): (torch.tensor([0, 1, 1, 2]),
                                torch.tensor([0, 0, 1, 1])),
    ('developer', 'develops', 'game'): (torch.tensor([0, 1]),
                                        torch.tensor([0, 1]))
    })
g.num_edges('plays')
g = dgl.add_edges(g, torch.tensor([3]), torch.tensor([3]), etype='plays')
g.num_edges('plays')

In [ ]:
g = dgl.graph((torch.tensor([0, 1]), torch.tensor([1, 2])))
g.num_nodes()
g = dgl.add_nodes(g, 2)
g.num_nodes()

In [ ]:
g.ndata['h'] = torch.ones(5, 1)
g = dgl.add_nodes(g, 1)
g.ndata['h']

In [ ]:
g = dgl.add_nodes(g, 1, {'h': torch.ones(1, 1), 'w': torch.ones(1, 1)})
g.ndata['h']

In [ ]:
g.ndata['w']

In [ ]:
g = dgl.heterograph({
    ('user', 'plays', 'game'): (torch.tensor([0, 1, 1, 2]),
                                torch.tensor([0, 0, 1, 1])),
    ('developer', 'develops', 'game'): (torch.tensor([0, 1]),
                                        torch.tensor([0, 1]))
    })
g.num_nodes('user')
g = dgl.add_nodes(g, 2, ntype='user')
g.num_nodes('user')